### ISSUE TITLE
Replication slots are currently not supported in Aurora

### ISSUE THREAD

**Issue by Belyenochi** [apache/aurora#49]
Hi,every hacker!
  Before PostgreSQL used WalRecord as a log, now I need to migrate to aurora. Should I change it? Can someone help me,thanks :-)

**Comment by jcohen** [comment]
Hi @Belyenochi, it seems you've gotten [Apache Aurora](http://aurora.apache.org/), a Mesos scheduler framework, confused with [Amazon Aurora](https://aws.amazon.com/rds/aurora/), a relational database service for AWS. Alas, there's not much we here in Apache Aurora can do to answer your question!
